name: Continuous Integration

# Trigger the workflow on push and pull requests targeting the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # 1. Job to set up the environment, install dependencies, and prepare the code
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
        php-version: [7.4, 8.0, 8.1]

    name: Setup (Node.js ${{ matrix.node-version }} / PHP ${{ matrix.php-version }})
    outputs:
      node_version: ${{ matrix.node-version }}
      php_version: ${{ matrix.php-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: npm install

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install PHP dependencies
        run: composer install

  # 2. Job for running linters on both JavaScript and PHP code
  lint:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node-version: [16, 18, 20]
        php-version: [7.4, 8.0, 8.1]
    steps:
      - name: Run ESLint (JavaScript)
        run: npm run lint:js

      - name: Run PHP_CodeSniffer (PHP)
        run: composer lint:php

  # 3. Job for running tests on both JavaScript and PHP code
  test:
    runs-on: ubuntu-latest
    needs: [setup, lint]
    strategy:
      matrix:
        node-version: [16, 18, 20]
        php-version: [7.4, 8.0, 8.1] 
    steps:
      - name: Run Tests (JavaScript)
        run: npm test

      - name: Run PHPUnit (PHP)
        run: vendor/bin/phpunit