name: Continuous Integration

# Trigger the workflow on push and pull requests targeting the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# 1. Job to set up the environment, install dependencies, and prepare the code
jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup (Node.js 18 / PHP 8.1)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm install

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install PHP dependencies
        run: composer install

  # 2. Job for running linters on both JavaScript and PHP code
  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run ESLint (JavaScript)
        run: npm run lint:js

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Run PHP_CodeSniffer (PHP)
        run: composer lint:php

  # 3. Job for running tests on both JavaScript and PHP code
  test:
    runs-on: ubuntu-latest
    needs: [setup, lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run Tests (JavaScript)
        run: npm test

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Run PHPUnit (PHP)
        run: vendor/bin/phpunit
